version: 2.1
orbs:
  python: circleci/python@2.0.3

workflows:
  build-app-with-test:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: ls -la
      - run:
          name: Install dependencies
          command: |
            pipenv --three
            pipenv install
      - run:
          name: Run tests
          command: |
            pipenv run pytest

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "15:e9:b6:64:49:8c:81:e3:e8:59:f1:7c:03:74:c0:52"
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
            cd ~/project/
            ssh -v imlogang@ssh.pythonanywhere.com "cd pythonanywhere; git pull"
